import { MAP_WIDTH, MAP_HEIGHT } from "../data/map.js?v=075-camera-lock-20260730";
import { drawOperator } from "./presentation/operator-renderer.js?v=075-camera-lock-20260730";
import { drawWorldEntity } from "./presentation/world-entity-renderer.js?v=075-camera-lock-20260730";
import { findEntity } from "./world-entities.js?v=075-camera-lock-20260730";

export class Renderer{
 constructor(canvas,camera){this.canvas=canvas;this.context=canvas.getContext("2d",{alpha:false});this.camera=camera;this.dpr=1;this.lastOperatorRenderError=null;}
 resize(){const rect=this.canvas.getBoundingClientRect();this.dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(rect.width*this.dpr));this.canvas.height=Math.max(1,Math.round(rect.height*this.dpr));this.context.setTransform(this.dpr,0,0,this.dpr,0,0);this.camera.resize(rect.width,rect.height);}
 render(game){const ctx=this.context,w=this.canvas.clientWidth,h=this.canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-Math.round(this.camera.x),-Math.round(this.camera.y));this.#drawGround(ctx,game);this.#drawRoad(ctx,game.map.road);this.#drawTrail(ctx,game.map.trail);this.#drawBrush(ctx,game.map.brush);this.#drawExtraction(ctx,game.map.extraction);this.#drawSiteGround(ctx,game.map.site);this.#drawCulvert(ctx,game);this.#drawShed(ctx,game.map.shed);this.#drawWildlife(ctx,game);this.#drawDepthSortedActors(ctx,game);this.#drawMapBorder(ctx);ctx.restore();if(game.weather==="Rain")this.#drawRain(ctx,w,h);}
 #drawTrail(ctx,trail){ctx.save();ctx.strokeStyle="rgba(112,97,70,.42)";ctx.lineWidth=86;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();ctx.moveTo(trail[0].x,trail[0].y);for(const p of trail.slice(1))ctx.lineTo(p.x,p.y);ctx.stroke();ctx.strokeStyle="rgba(188,169,126,.22)";ctx.lineWidth=58;ctx.stroke();ctx.restore();}
 #drawCulvert(ctx,game){const c=game.map.culvert,water=findEntity(game.entities,"culvert_water_01");ctx.save();ctx.fillStyle=game.weather==="Rain"?"rgba(67,102,108,.72)":"rgba(76,113,116,.62)";const grow=water?.depth==="rising"?38:0;ctx.beginPath();ctx.roundRect(c.water.x-grow,c.water.y-grow/2,c.water.width+grow*2,c.water.height+grow,45);ctx.fill();ctx.strokeStyle="rgba(210,225,213,.22)";ctx.lineWidth=3;for(let y=c.water.y+24;y<c.water.y+c.water.height;y+=35){ctx.beginPath();ctx.moveTo(c.water.x+25,y);ctx.quadraticCurveTo(c.water.x+180,y-10,c.water.x+320,y);ctx.quadraticCurveTo(c.water.x+460,y+10,c.water.x+c.water.width-25,y);ctx.stroke();}ctx.fillStyle="#66685d";ctx.fillRect(c.x,c.y,180,80);ctx.fillRect(c.x,c.y+c.height-80,180,80);ctx.fillStyle="#353d38";ctx.beginPath();ctx.arc(c.x+180,c.y+c.height/2,92,-Math.PI/2,Math.PI/2);ctx.lineTo(c.x+180,c.y+c.height/2-92);ctx.fill();ctx.fillStyle="rgba(35,43,38,.75)";ctx.font="700 22px system-ui";ctx.fillText("NORTH CULVERT",c.x-80,c.y-28);ctx.restore();}
 #drawRain(ctx,w,h){ctx.save();ctx.strokeStyle="rgba(215,225,220,.34)";ctx.lineWidth=1.4;const t=performance.now()*.22;for(let i=0;i<95;i++){const x=(i*73+t)%w,y=(i*127+t*1.7)%h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-8,y+18);ctx.stroke();}ctx.restore();}
 #drawWildlife(ctx,game){ctx.save();for(const bird of game.wildlife){ctx.globalAlpha=game.weather==="Fog"?.22:.45;ctx.fillStyle="#d7d0a6";ctx.beginPath();ctx.ellipse(bird.x,bird.y,3.4,1.8,Math.sin(bird.phase)*.5,0,Math.PI*2);ctx.fill();}ctx.restore();}
 #drawDepthSortedActors(ctx,game){const targetedId=game.interaction.targetId,entries=game.map.obstacles.map(o=>({y:o.y+o.radius*.5,draw:()=>o.type==="tree"?this.#drawTree(ctx,o):this.#drawRock(ctx,o)}));for(const entity of game.entities){if(entity.revealed===false)continue;if(entity.type==="hazard")continue;if(entity.type==="item"&&entity.locationType!=="world"&&entity.locationType!=="stored"||entity.type==="item"&&!entity.revealed)continue;entries.push({y:entity.groundY,draw:()=>drawWorldEntity(ctx,entity,{targeted:entity.id===targetedId})});}for(const actor of game.actors){const renderActor=actor.seated?{...actor,y:actor.y+10,vx:0,vy:0}:actor;entries.push({y:actor.groundY-1,draw:()=>{if(actor.condition==="bleeding"){ctx.save();ctx.fillStyle="rgba(111,45,40,.52)";ctx.beginPath();ctx.ellipse(actor.x+8,actor.y+31,13,6,-.2,0,Math.PI*2);ctx.fill();ctx.restore();}ctx.save();if(actor.condition==="bleeding"||actor.condition==="injured"){ctx.translate(actor.x,actor.y);ctx.rotate(-.08);ctx.translate(-actor.x,-actor.y);}drawOperator(ctx,renderActor,null);ctx.restore();}});}game.operator.backpackLoadRatio=game.inventory.getUsedPips()/game.backpack.capacityPips;const carried=game.getHeldItem();entries.push({y:game.operator.y+game.operator.radius,draw:()=>this.#drawPlayer(ctx,game.operator,carried)});entries.sort((a,b)=>a.y-b.y);for(const entry of entries){try{entry.draw();}catch(error){console.error("Fieldwork draw entry failed",error);}}}
 #drawPlayer(ctx,operator,carried){try{drawOperator(ctx,operator,carried);this.lastOperatorRenderError=null;}catch(error){this.lastOperatorRenderError=String(error?.message||error);console.error("Fieldwork operator render failed",error);ctx.save();ctx.fillStyle="#e9a13f";ctx.strokeStyle="#18211c";ctx.lineWidth=4;ctx.beginPath();ctx.arc(operator.x,operator.y,22,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle="#18211c";ctx.font="700 14px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("M",operator.x,operator.y);ctx.restore();}}
 #drawGround(ctx,game){ctx.fillStyle=game.weather==="Fog"?"#7d8878":game.weather==="Cloudy"?"#6f7b68":game.weather==="Rain"?"#59685a":"#758467";ctx.fillRect(0,0,MAP_WIDTH,MAP_HEIGHT);ctx.fillStyle="rgba(49,62,48,.09)";for(let y=30;y<MAP_HEIGHT;y+=70)for(let x=20+((y/70)%2)*24;x<MAP_WIDTH;x+=86){ctx.beginPath();ctx.ellipse(x,y,3,8,.3,0,Math.PI*2);ctx.fill();}}
 #drawRoad(ctx,road){const xs=road.map(p=>p.x),ys=road.map(p=>p.y);ctx.fillStyle="#8b8068";ctx.fillRect(Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)-Math.min(...ys));ctx.strokeStyle="rgba(46,42,34,.22)";ctx.lineWidth=6;ctx.setLineDash([24,34]);ctx.beginPath();ctx.moveTo(0,800);ctx.lineTo(2600,800);ctx.stroke();ctx.setLineDash([]);}
 #drawBrush(ctx,brush){for(const p of brush){ctx.fillStyle="rgba(47,77,50,.38)";for(let i=0;i<12;i++){const a=i/12*Math.PI*2,r=p.radius*(.45+i%3*.16);ctx.beginPath();ctx.arc(p.x+Math.cos(a)*r*.55,p.y+Math.sin(a)*r*.45,32+i%4*5,0,Math.PI*2);ctx.fill();}}}
 #drawExtraction(ctx,e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle="rgba(222,158,75,.13)";ctx.strokeStyle="rgba(235,176,96,.68)";ctx.lineWidth=5;ctx.setLineDash([14,12]);ctx.beginPath();ctx.arc(0,0,e.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="rgba(31,40,34,.9)";ctx.fillRect(-44,-18,88,36);ctx.fillStyle="#e4d5b8";ctx.font="700 16px system-ui";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText("RETURN",0,0);ctx.restore();}
 #drawSiteGround(ctx,site){ctx.fillStyle="rgba(119,105,77,.2)";ctx.beginPath();ctx.roundRect(660,340,1420,1000,80);ctx.fill();ctx.fillStyle="rgba(86,79,62,.18)";ctx.beginPath();ctx.roundRect(site.workArea.x-40,site.workArea.y-30,site.workArea.width+80,site.workArea.height+90,28);ctx.fill();ctx.fillStyle="rgba(38,46,39,.72)";ctx.font="700 18px system-ui";ctx.textAlign="left";ctx.fillText("OLD MAINTENANCE PULL-OFF",1140,350);}
 #drawShed(ctx,s){ctx.fillStyle="rgba(26,31,27,.24)";ctx.fillRect(s.x+16,s.y+18,s.width,s.height);ctx.fillStyle="#5e6255";ctx.fillRect(s.x,s.y,s.width,s.height);ctx.fillStyle="#373d35";const t=s.wallThickness;ctx.fillRect(s.x,s.y,s.width,t);ctx.fillRect(s.x,s.y,t,s.height);ctx.fillRect(s.x+s.width-t,s.y,t,s.height);ctx.fillRect(s.x,s.y+s.height-t,s.doorGap.start,t);ctx.fillRect(s.x+s.doorGap.start+s.doorGap.width,s.y+s.height-t,s.width-s.doorGap.start-s.doorGap.width,t);ctx.fillStyle="#817459";ctx.fillRect(s.x+52,s.y+62,s.width-104,s.height-118);}
 #drawTree(ctx,t){ctx.fillStyle="rgba(20,28,22,.24)";ctx.beginPath();ctx.ellipse(t.x+12,t.y+15,t.radius*.95,t.radius*.65,.2,0,Math.PI*2);ctx.fill();ctx.fillStyle="#384b38";ctx.beginPath();ctx.arc(t.x,t.y,t.radius,0,Math.PI*2);ctx.fill();ctx.fillStyle="#52644b";ctx.beginPath();ctx.arc(t.x-t.radius*.2,t.y-t.radius*.22,t.radius*.7,0,Math.PI*2);ctx.fill();}
 #drawRock(ctx,r){ctx.fillStyle="rgba(24,29,25,.24)";ctx.beginPath();ctx.ellipse(r.x+8,r.y+10,r.radius,r.radius*.7,.1,0,Math.PI*2);ctx.fill();ctx.fillStyle="#686b61";ctx.beginPath();ctx.ellipse(r.x,r.y,r.radius,r.radius*.75,-.15,0,Math.PI*2);ctx.fill();}
 #drawMapBorder(ctx){ctx.strokeStyle="rgba(20,27,23,.5)";ctx.lineWidth=14;ctx.strokeRect(0,0,MAP_WIDTH,MAP_HEIGHT);}
}
