import test from "node:test";
import assert from "node:assert/strict";
import { CasualtyRecoveryRuntime } from "../js/ai-v2/actors/casualty-recovery-runtime.js";
import { CasualtyRecoveryPositionService } from "../js/ai-v2/position/casualty-recovery-position-service.js";
import { CasualtyCareExecutor } from "../js/ai-v2/execution/casualty-care-executor.js";
import { DragCasualtyAction } from "../js/ai-v2/actions/drag-casualty-action.js";
import { ApproachCasualtyAction } from "../js/ai-v2/actions/approach-casualty-action.js";

function actors(){
  const provider={id:"provider",name:"Provider",teamId:"team",x:0,y:0,radius:18,medical:{condition:"healthy",dead:false,unconscious:false},aiV2MedicalSupplies:{pressure_dressing:2}};
  const casualty={id:"casualty",name:"Ada",teamId:"team",x:60,y:0,radius:18,medical:{condition:"serious",dead:false,unconscious:false}};
  return{provider,casualty};
}
function obligation(){return{id:"staffed:care",actorId:"provider",teamId:"team",concernId:"casualty:casualty",concernKind:"friendly_casualty",subjectId:"casualty",responsibility:"carrier_or_aid_provider",desiredEffect:"recover_friendly_casualty",authorityTier:500,priority:1.2,urgency:.9,status:"accepted"};}
function assessment(now=10,{condition="serious",bleeding=.08,need="pressure_dressing",mobility="requires_assisted_movement",immediateDanger=true}={}){return{condition,conscious:condition!=="unconscious",dead:false,bleeding,blood:.8,shock:.2,mobility,immediateDanger,treatmentNeed:need?{type:need}:null,assessedAt:now,assessedBy:"provider"};}
function knowledge(casualty,recordAssessment){return{getPersonalCasualties(){return[];},getReceivedCasualties(){return[];},getTeamCasualties(){return[{subjectId:casualty.id,assessmentRevision:1,reportedAt:recordAssessment.assessedAt,approximatePosition:{x:casualty.x,y:casualty.y},assessment:recordAssessment}];}};}
function mission(){return{recoveryPlan:{interactionRange:92,reportRange:520,dragSpeedMultiplier:.46,arrivalRadius:13,claimSpacing:62,recoveryPoint:{x:180,y:0},label:"Aid point"}};}
function game(provider,casualty){return{scenarioMode:"live",livingSandbox:{liveMode:true},actors:[provider,casualty],map:{obstacles:[]},wounds:{getTreatmentNeed(){return{type:"pressure_dressing"};},getAssessment(){return{};}}};}
function brain(){return{submissions:[],submit(value){this.submissions.push(value);}};}
function noThreatPictures(){return{get(){return{threatPoint:null,incomingFire:[],securitySupport:.5};}};}
function exposedPictures(){return{get(){return{threatPoint:{x:-240,y:0},incomingFire:[{id:"shot"}],securitySupport:.1};}};}
function exposedCover(){return{protectionAt({point}){return{protection:point.x>120?.84:.08};},buildSlots(){return[{id:"safe:right",sourceType:"wall",variant:"right",point:{x:180,y:0},utility:{protection:.84}}];}};}
function evaluate({recordAssessment=assessment(),pictures=noThreatPictures(),cover=null,casualtyPatch={},providerPatch={},now=10,procedure=null,teamProcedures=null}={}){
  const {provider,casualty}=actors();Object.assign(provider,providerPatch);Object.assign(casualty,casualtyPatch);if(casualtyPatch.medical)casualty.medical={condition:"serious",dead:false,unconscious:false,...casualtyPatch.medical};
  const b=brain();const runtime=new CasualtyRecoveryRuntime({brain:b,positionService:new CasualtyRecoveryPositionService()});
  const rec=runtime.evaluateAndSubmit({game:game(provider,casualty),actor:provider,role:{roleId:"aid_provider"},procedure,mission:mission(),obligation:obligation(),casualtyKnowledge:recordAssessment?knowledge(casualty,recordAssessment):{getPersonalCasualties(){return[];},getReceivedCasualties(){return[];},getTeamCasualties(){return[];}},tacticalPictures:pictures,directionalCover:cover,actorObligations:{markBlocked(){}},teamProcedures,now});
  return{provider,casualty,b,runtime,rec};
}

test("safe casualty is treated in place without authored recovery-point choreography",()=>{const {rec,b}=evaluate();assert.equal(rec.selected.type,"TreatAssignedCasualty");assert.equal(b.submissions[0].source,"casualty_recovery_runtime");assert.equal(rec.candidates.some(item=>item.type==="DragCasualty"),false);});
test("severely exposed casualty can be dragged before treatment",()=>{const {rec}=evaluate({pictures:exposedPictures(),cover:exposedCover()});assert.equal(rec.selected.type,"DragCasualty");assert.equal(rec.position.betterGroundAvailable,true);assert.ok(rec.position.bestRecoveryPosition.protection>.7);});
test("critical treatment urgency can beat a merely better recovery position",()=>{const mildGainCover={protectionAt({point}){return{protection:point.x>120?.48:.24};},buildSlots(){return[{id:"cover",sourceType:"wall",variant:"center",point:{x:150,y:0},utility:{protection:.48}}];}};const pictures={get(){return{threatPoint:{x:-260,y:0},incomingFire:[],securitySupport:.3};}};const recAssessment=assessment(10,{condition:"critical",bleeding:.2,need:"pressure_dressing",mobility:"requires_assisted_movement",immediateDanger:true});const {rec}=evaluate({recordAssessment:recAssessment,pictures,cover:mildGainCover,casualtyPatch:{medical:{condition:"critical",unconscious:false}}});assert.equal(rec.selected.type,"TreatAssignedCasualty");});
test("without a fresh assessment, acceptable ground produces assessment rather than a ritual drag",()=>{const {rec}=evaluate({recordAssessment:null});assert.equal(rec.selected.type,"AssessCasualty");});
test("catastrophic exposure may move an unassessed casualty before assessment",()=>{const {rec}=evaluate({recordAssessment:null,pictures:exposedPictures(),cover:exposedCover()});assert.equal(rec.selected.type,"DragCasualty");assert.ok(rec.candidates.some(item=>item.type==="AssessCasualty"));});
test("fresh assessment suppresses redundant AssessCasualty proposals",()=>{const {rec}=evaluate();assert.equal(rec.assessmentFresh,true);assert.equal(rec.candidates.some(item=>item.type==="AssessCasualty"),false);});
test("legacy recovery procedure is advanced from achieved facts rather than choosing the method",()=>{const events=[];const procedure={procedureId:"recovery",phase:{id:"assess_condition"}};const teamProcedures={notifyEvent(value){events.push(value);}};const {rec}=evaluate({procedure,teamProcedures});assert.equal(rec.selected.type,"TreatAssignedCasualty");assert.equal(events[0].event,"casualty_assessed");assert.equal(events[0].data.desiredEffectDriven,true);});
test("drag interruption releases patient control while obligation ownership can persist",()=>{const {provider,casualty}=actors();const care=new CasualtyCareExecutor();const claims={claim(){return{ok:true};},renew(){},release(){}};const action=new DragCasualtyAction({actorId:provider.id,directive:{obligationId:"staffed:care",casualtyId:casualty.id,destination:{x:180,y:0},interactionRange:92,initialDistance:120,policy:{}}});const g=game(provider,casualty);action.start(0,{game:g,services:{casualtyCare:care,destinationClaims:claims}});assert.equal(care.getController(casualty.id),provider.id);action.onInterrupted({game:g,services:{casualtyCare:care,destinationClaims:claims},now:.5});assert.equal(care.getController(casualty.id),null);});
test("casualty drag delegates movement to 3.2D spatial-intent navigation",()=>{const {provider,casualty}=actors();const care=new CasualtyCareExecutor();let captured=null;const locomotion={moveWithIntent(actor,intent){captured=intent;actor.vx=10;actor.vy=0;return{arrived:false,failed:false,distance:100};}};care.dragToward({game:game(provider,casualty),responder:provider,patient:casualty,destination:{x:200,y:0},delta:.1,locomotion,now:2});assert.equal(captured.kind,"casualty_drag");assert.equal(captured.allowRetreat,true);});
test("ApproachCasualty continuation is owned by the obligation rather than procedure phase",()=>{const {provider,casualty}=actors();provider.x=-200;const action=new ApproachCasualtyAction({actorId:provider.id,directive:{obligationId:"staffed:care",casualtyId:casualty.id,interactionRange:92,initialDistance:260,policy:{}}});const g=game(provider,casualty);assert.equal(action.canContinue({game:g,services:{actorObligations:{getById(){return{status:"accepted"};}}}}),true);assert.equal(action.canContinue({game:g,services:{actorObligations:{getById(){return{status:"resolved"};}}}}),false);});
