const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,Number(v)||0));
const t=(id,label,value,weight)=>({id,label,value:clamp(value),weight,contribution:clamp(value)*weight});
function option(spec){return Object.freeze({...spec,evaluate({ledger,encounter}={}){if(!ledger||!spec.eligible({ledger,encounter}))return null;const contributions=spec.terms(ledger);return{id:spec.id,label:spec.label,summary:spec.summary,score:clamp(spec.base+contributions.reduce((s,x)=>s+x.contribution,0)+(ledger.responseBias?.[spec.id]??0)),bias:ledger.responseBias?.[spec.id]??0,contributions,reason:spec.reason(ledger),eligible:true};}});}
const active=({ledger})=>ledger.contactResolutionRequired>0&&ledger.sameFaction<=0&&ledger.cooperating<=0&&ledger.boundaryTrigger<=0&&ledger.warningIssued<=0&&ledger.warningHeard<=0;
export const AI_V2_2_5_RESPONSE_OPTIONS=Object.freeze([
 option({id:"engage_contact",label:"Engage Contact",summary:"Take ready positions and enter a bounded hostile-contact posture.",base:.34,eligible:({ledger})=>active({ledger})&&ledger.hostileEvidence>0,terms:l=>[t("hostile","relationship or evidence is hostile",l.hostileEvidence,.34),t("relevance","contact is materially relevant",l.contactResolutionRequired,.22),t("conflict","routes or objectives conflict",Math.max(l.routeConflict,l.objectiveConflict),.18),t("security","security doctrine supports control",l.securityOrientation,.12)],reason:()=>"The opposing team is both materially relevant and hostile; ordinary work yields to a bounded security response."}),
 option({id:"contest_access",label:"Contest Access",summary:"Stop normal work, occupy local security positions, and deny unopposed access.",base:.27,eligible:({ledger})=>active({ledger})&&ledger.objectiveConflict>0&&ledger.hostileEvidence<=0&&ledger.deconflicting<=0,terms:l=>[t("objective","both teams need the same objective",l.objectiveConflict,.34),t("route","their movement conflicts",l.routeConflict,.14),t("mission","yielding would abandon useful work",l.missionValue,.18),t("security","the team can establish presence",l.securityOrientation,.12)],reason:()=>"The teams require the same limited access; the area must be contested rather than worked in parallel without tension."}),
 option({id:"avoid_contact",label:"Avoid Contact",summary:"Yield space, select a passing side, and restore separation before resuming the mission.",base:.25,eligible:({ledger})=>active({ledger})&&ledger.hostileEvidence<=0&&ledger.objectiveConflict<=0,terms:l=>[t("relevance","the contact requires resolution",l.contactResolutionRequired,.28),t("route","projected movement intersects",l.routeConflict,.20),t("mobility","the team can move around",l.mobilityOrientation,.18),t("preservation","spacing protects the team",l.teamPreservation,.14),t("exit","lateral space exists",l.exitOptions,.10)],reason:()=>"The opposing team is close enough or on a conflicting route that continuing unchanged would be incoherent; preserve the mission by creating separation."})
]);
